### ISSUE TITLE
Windows app keeps crashing

### ISSUE THREAD

**Issue by Keref** [AugurProject/augur-ui#1991]
It worked for a while, but it keeps crashing regularly, some time after connecting to an Ethereum node, using Metamask. Crashes between 2s to 10-15 minutes after connecting to a mainnet Ethereum node.

Are there logs somewhere? Can't find in the app directory.

**Comment by Keref** [comment]
One crash:
`[2018-07-11 12:43:11.894] [info] 
[2018-07-11 12:43:12.414] [info] new block: 5942832 1531284182
[2018-07-11 12:43:12.435] [info] Processing 1 logs
[2018-07-11 12:43:12.435] [error] Fatal Error, shutting down servers Error: market and outcome not found
    at db.first.from.where.asCallback (C:\Users\lapin\AppData\Local\Programs\augur\resources\app.asar\node_modules\augur-node\build\blockchain\log-processors\order-created.js:20:29)
    at tryCatcher (C:\Users\lapin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\Users\lapin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\nodeify.js:22:30)
    at Promise._settlePromise (C:\Users\lapin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (C:\Users\lapin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\lapin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\lapin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\lapin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\lapin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

[2018-07-11 12:43:12.435] [error] Error: market and outcome not found
    at db.first.from.where.asCallback (C:\Users\lapin\AppData\Local\Programs\augur\resources\app.asar\node_modules\augur-node\build\blockchain\log-processors\order-created.js:20:29)
    at tryCatcher (C:\Users\lapin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\Users\lapin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\nodeify.js:22:30)
    at Promise._settlePromise (C:\Users\lapin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (C:\Users\lapin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\lapin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\lapin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\lapin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\lapin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

[2018-07-11 12:43:12.482] [info] Stopping Augur Node Server
[2018-07-11 12:43:12.482] [info] Stopping Augur Node Server
[2018-07-11 12:43:12.497] [info] Stopping Augur UI Server
[2018-07-11 12:43:12.497] [info] Failed to startup: market and outcome not found`

Another one:
`[2018-07-11 17:43:52.915] [info] new block: 5944037 1531302184
[2018-07-11 17:43:52.933] [info] new block: 5944038 1531302218
[2018-07-11 17:43:52.948] [info] Processing 2 logs
[2018-07-11 17:43:52.955] [error] Fatal Error, shutting down servers Error: SQLITE_CONSTRAINT: CHECK constraint failed: nonnegativeBalance

[2018-07-11 17:43:52.955] [error] Error: SQLITE_CONSTRAINT: CHECK constraint failed: nonnegativeBalance

[2018-07-11 17:43:53.005] [info] Stopping Augur Node Server
[2018-07-11 17:43:53.005] [info] Stopping Augur Node Server
[2018-07-11 17:43:53.006] [info] Stopping Augur UI Server
[2018-07-11 17:43:53.007] [info] Failed to startup: update `balances` set `balance` = '-200000000000000000000' where `token` = '0x1985365e9f78359a9b6ad760e32412f4a445e862' and `owner` = '0x58c444cc2658bb485f7985d5889b1d5857614f31' - SQLITE_CONSTRAINT: CHECK constraint failed: nonnegativeBalance`

**Comment by tobutridaz** [comment]
Same for me. From the log
````
[2018-07-11 11:55:53.103] [info] Stopping Augur Node Server
[2018-07-11 11:55:53.103] [info] Stopping Augur Node Server
[2018-07-11 11:55:53.105] [info] Stopping Augur UI Server[2018-07-11 11:55:46.555] [info] {"id":101,"jsonrpc":"2.0","method":"getMarketPriceCandlesticks","params":{"marketId":"0x5d192f598ff29318013b3f269ae37590aa75b5f9","period":3600,"start":1531213200,"end":1531302925,"outcome":"1"}}
[2018-07-11 11:55:46.796] [info] 
[2018-07-11 11:55:47.794] [info] 
[2018-07-11 11:55:48.792] [info] 
[2018-07-11 11:55:49.801] [info] 
[2018-07-11 11:55:50.806] [info] 
[2018-07-11 11:55:51.795] [info] 
[2018-07-11 11:55:52.795] [info] 
[2018-07-11 11:55:53.015] [info] new block: 5944086 1531302896
[2018-07-11 11:55:53.025] [info] Processing 57 logs
[2018-07-11 11:55:53.055] [error] Fatal Error, shutting down servers Error: order not found
    at db.first.from.where.asCallback (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\augur-node\build\blockchain\log-processors\order-filled\index.js:36:37)
    at tryCatcher (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\nodeify.js:22:30)
    at Promise._settlePromise (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

[2018-07-11 11:55:53.055] [error] Error: order not found
    at db.first.from.where.asCallback (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\augur-node\build\blockchain\log-processors\order-filled\index.js:36:37)
    at tryCatcher (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\nodeify.js:22:30)
    at Promise._settlePromise (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2018-07-11 11:55:53.105] [info] Failed to startup: order not found
````

**Comment by xenoexclusive** [comment]
As you can see from these open issues, this has been opened numerous times with many duplicates:

https://github.com/AugurProject/augur-app/issues/83
https://github.com/AugurProject/augur-app/issues/95
https://github.com/AugurProject/augur-app/issues/99

etc.
