### ISSUE TITLE
augur-ui installing with errors

### ISSUE THREAD

**Issue by kevinreilly** [AugurProject/augur-ui#2172]
I can't for the life of me get augur-ui installed locally on OSX. Following the [UI only instructions](https://github.com/AugurProject/augur-ui/blob/master/docs/ui-dev-easy-start.md), with the latest Node, NPM, and Yarn installed with Homebrew as well as Docker and Xcode, when I run `yarn`, I get the output below. I'm mostly a frontend dev so I'm not that great at debugging this kind of stuff. Hopefully someone out there can help me out so I can start contributing to this repo.
```
osx:augur-ui-5.3.0 kevin$ yarn
yarn install v1.9.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[----------------------------------------------------------------------] 0/1991(node:32020) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[4/5] 🔗  Linking dependencies...
warning "augur.js > augur-core > solidity-coverage > ethereumjs-testrpc-sc > webpack-cli@2.1.5" has incorrect peer dependency "webpack@^4.0.0".
warning "react-dates > react-with-styles@2.4.0" has unmet peer dependency "react-with-direction@^1.1.0".
warning " > babel-plugin-rewire@1.1.0" has unmet peer dependency "babel-template@^6.2.0".
warning " > babel-plugin-rewire@1.1.0" has unmet peer dependency "babel-types@^6.2.0".
warning " > eslint-import-resolver-babel-module@3.0.0" has incorrect peer dependency "babel-plugin-module-resolver@^2.5.0".
warning "stylelint > postcss-html@0.11.0" has unmet peer dependency "postcss-sass@>=0.2.0".
warning " > stylelint-config-standard@16.0.0" has incorrect peer dependency "stylelint@^7.8.0".
[5/5] 📃  Building fresh packages...
[11/13] ⠈ puppeteer
[8/13] ⠈ node-hid
[-/13] ⠈ waiting...
[9/13] ⠈ secp256k1
error /Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.31
node-pre-gyp info using node@10.8.0 | darwin | x64
node-pre-gyp info check checked for "/Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid/build/Release/HID.node" (not found)
node-pre-gyp http GET https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-hid@0.5.4 and node@10.8.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Tried to download(undefined): https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-hid@0.5.4 and node@10.8.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http Connection closed while downloading tarball file 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.8.0 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.8.0 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.8.0 | darwin | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.8.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/kevin/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kevin/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kevin/.node-gyp/10.8.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/kevin/.node-gyp/10.8.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/kevin/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/kevin/.node-gyp/10.8.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/kevin/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kevin/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kevin/.node-gyp/10.8.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/kevin/.node-gyp/10.8.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/kevin/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/kevin/.node-gyp/10.8.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.8.0 | darwin | x64
gyp info ok 
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/hidapi/hidapi/mac/hid.o
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.8.0 | darwin | x64
../hidapi/mac/hid.c:252:20: warning: comparison of integers of different signs: 'CFIndex' (aka 'long') and 'size_t' (aka 'unsigned long') [-Wsign-compare]
                if (chars_copied == len)
                    ~~~~~~~~~~~~ ^  ~~~
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/hidapi/hidapi/mac/hid.o
1 warning generated.
../hidapi/mac/hid.c:252:20: warning: comparison of integers of different signs: 'CFIndex' (aka 'long') and 'size_t' (aka 'unsigned long') [-Wsign-compare]
                if (chars_copied == len)
                    ~~~~~~~~~~~~ ^  ~~~
  LIBTOOL-STATIC Release/hidapi.a
1 warning generated.
  CXX(target) Release/obj.target/HID/src/HID.o
  LIBTOOL-STATIC Release/hidapi.a
  CXX(target) Release/obj.target/HID/src/HID.o
../src/HID.cc:209:45: error: no matching member function for call to 'NewInstance'
    Local<Object> buf = nodeBufConstructor->NewInstance(1, nodeBufferArgs);
                        ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/Users/kevin/.node-gyp/10.8.0/include/node/v8.h:3956:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8.h:3953:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/HID.cc:233:20: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  iocb->_callback->Call(2, argv);
                   ^
../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/HID.cc:296:41: error: too few arguments to function call, single argument 'context' was not specified
  const int timeout = info[0]->ToUint32()->Value();
                      ~~~~~~~~~~~~~~~~~ ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8.h:2406:3: note: 'ToUint32' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Uint32> ToUint32(
  ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8config.h:416:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/HID.cc:316:28: error: too few arguments to function call, single argument 'context' was not specified
      || info[1]->ToUint32()->Value() == 0) {
         ~~~~~~~~~~~~~~~~~ ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8.h:2406:3: note: 'ToUint32' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Uint32> ToUint32(
  ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8config.h:416:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/HID.cc:320:46: error: too few arguments to function call, single argument 'context' was not specified
  const uint8_t reportId = info[0]->ToUint32()->Value();
                           ~~~~~~~~~~~~~~~~~ ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8.h:2406:3: note: 'ToUint32' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Uint32> ToUint32(
  ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8config.h:416:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/HID.cc:322:41: error: too few arguments to function call, single argument 'context' was not specified
  const int bufSize = info[1]->ToUint32()->Value();
                      ~~~~~~~~~~~~~~~~~ ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8.h:2406:3: note: 'ToUint32' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Uint32> ToUint32(
  ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8config.h:416:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/HID.cc:406:37: warning: 'Value' is deprecated [-Wdeprecated-declarations]
        serialPointer = (wchar_t*) *v8::String::Value(info[2]);
                                    ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8.h:2876:5: note: 'Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version", explicit Value(Local<v8::Value> obj));
    ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/HID.cc:209:45: error: no matching member function for call to 'NewInstance'
    Local<Object> buf = nodeBufConstructor->NewInstance(1, nodeBufferArgs);
                        ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/Users/kevin/.node-gyp/10.8.0/include/node/v8.h:3956:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8.h:3953:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/HID.cc:233:20: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  iocb->_callback->Call(2, argv);
                   ^
../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/HID.cc:296:41: error: too few arguments to function call, single argument 'context' was not specified
  const int timeout = info[0]->ToUint32()->Value();
                      ~~~~~~~~~~~~~~~~~ ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8.h:2406:3: note: 'ToUint32' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Uint32> ToUint32(
  ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8config.h:416:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/HID.cc:316:28: error: too few arguments to function call, single argument 'context' was not specified
      || info[1]->ToUint32()->Value() == 0) {
         ~~~~~~~~~~~~~~~~~ ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8.h:2406:3: note: 'ToUint32' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Uint32> ToUint32(
  ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8config.h:416:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
2 warnings and 5 errors generated.
../src/HID.cc:320:46: error: too few arguments to function call, single argument 'context' was not specified
  const uint8_t reportId = info[0]->ToUint32()->Value();
                           ~~~~~~~~~~~~~~~~~ ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8.h:2406:3: note: 'ToUint32' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Uint32> ToUint32(
  ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8config.h:416:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
make: *** [Release/obj.target/HID/src/HID.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/kevin/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/10.8.0/bin/node" "/Users/kevin/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid/build/Release/HID.node" "--module_name=HID" "--module_path=/Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid/build/Release"
gyp ERR! cwd /Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/10.8.0/bin/node /Users/kevin/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid/build/Release/HID.node --module_name=HID --module_path=/Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/10.8.0/bin/node" "/Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid
node-pre-gyp ERR! node -v v10.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok 
../src/HID.cc:322:41:Failed to execute '/usr/local/Cellar/node/10.8.0/bin/node /Users/kevin/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid/build/Release/HID.node --module_name=HID --module_path=/Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid/build/Release' (1)
 error: too few arguments to function call, single argument 'context' was not specified
  const int bufSize = info[1]->ToUint32()->Value();
                      ~~~~~~~~~~~~~~~~~ ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8.h:2406:3: note: 'ToUint32' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Uint32> ToUint32(
  ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8config.h:416:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/HID.cc:406:37: warning: 'Value' is deprecated [-Wdeprecated-declarations]
        serialPointer = (wchar_t*) *v8::String::Value(info[2]);
                                    ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8.h:2876:5: note: 'Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version", explicit Value(Local<v8::Value> obj));
    ^
/Users/kevin/.node-gyp/10.8.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
2 warnings and 5 errors generated.
make: *** [Release/obj.target/HID/src/HID.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/kevin/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/10.8.0/bin/node" "/Users/kevin/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid/build/Release/HID.node" "--module_name=HID" "--module_path=/Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid/build/Release"
gyp ERR! cwd /Users/kevin/Downloads/augur-ui-5.3.0/node_modules/node-hid
gyp ERR! node -v v10.8.0
```

**Comment by bthaile** [comment]
What version of node, npm and yarn are you working with.

The versions that work for me are:

node: v9.11.1
npm: 5.6.0
yarn: 1.7.0
docker: Docker version 18.06.0-ce

**Comment by kevinreilly** [comment]
@bthaile That did the trick. Downgraded to Node (v8.11.3) and NPM (5.6.0) and the build runs without issue now. Is this something we should add to the documentation? Thanks for your help.

**Comment by bthaile** [comment]
If mem serves the issue you were seeing with node version 10 has to do with node-hid. I think it's known to be broken. The reason we are using the non-stable version of node.

I can add to UI docs.

**Comment by kevinreilly** [comment]
@bthaile - I'm not sure if this is relevant, but when I try to view my local build on localhost, I'm receiving the following error page in the browser:
```
NETWORK MISMATCH
MetaMask is connected to the wrong Ethereum network.
Please set the MetaMask network to: 102
```
I'm connected to Localhost 8545 in Metamask.

**Comment by justinbarry** [comment]
@kevinreilly Are you running augur-app locally?

**Comment by bthaile** [comment]
@kevinreilly also, are you running our private ethereum local docker image?

I think network id of 102 is our geth:pop image. What chain are you trying to connect to?

**Comment by kevinreilly** [comment]
@justinbarry, @bthaile - I'm just following the instruction [here](https://github.com/AugurProject/augur-ui/blob/master/docs/ui-dev-easy-start.md). There's no mention of having to run augur-app or a private ethereum local docker image.

**Comment by bthaile** [comment]
npm run docker:spin-up

This starts up 2 docker images. One is the local private ethereum geth node, the other is augur-node.

**Comment by bthaile** [comment]
Try, clearing your localStorage. In your browser which is running http://localhost:8080, open web console run this command localStorage.clear()

This will clear out any settings. Like old setting that augur-ui uses to connect with ethereum nodes or remote augur-nodes. 

Make sure to hard refresh your browser, 
Make sure mera mask is connected to local
Click on accounts then ‘connect to meta mask’

**Comment by bthaile** [comment]
Also invite you to discord to as questions in the #dev channel.
https://discordapp.com/invite/faud6Fx

**Comment by kevinreilly** [comment]
@bthaile - Clearing localStorage did the trick. Thanks a lot!
